### PR TITLE
 typescript refactor

### PR DESCRIPTION
**Pull request by Julusian**

### CODE REVIEW

**Comment by bevanjkay** [comment]
@Julusian Big refactor! I guess it's time to dip my toes into Typescript. 

I can help with some testing in the next couple of days.

**Comment by Julusian** [comment]
It's not quite done yet, a couple of the actions related to the active device aren't implemented.
But most the rest has had a quick test and looks to work fine.

I'm also tempted to do some action reshuffling, to combine some very similar actions. Eg play, pause and play/pause into a single action that let's you choose how it behaves.
But not sure it's worth the effort

**Comment by Julusian** [comment]
@bevanjkay ok, I am happy with this now. It could do with some more testing, but I think it should be fine so I am tempted to merge it and deal with issues if anything gets reported

**Comment by Julusian** [comment]
This has an annoying bug where sometimes the api call never returns, and never times out https://github.com/thelinmichael/spotify-web-api-node/issues/165

**Pull request merged**
